publishdir: ./generated

baseURL: "https://axaratox.dev/"
title: "axaratox"
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  env: production
  title: "axaratox"
  description: "axaratox's blog & playground"
  keywords: [axaratox, blog]
  DateFormat: "02/01/2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true
    disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-icon.png"
    safari_pinned_tab: "apple-icon.png"

  label:
    text: "axaratox"

  profileMode:
    enabled: true
    title: Welcome
    imageUrl: "./x.webp"
    imageWidth: 150
    imageHeight: 150
    imageTitle: logo
    buttons:
      - name: Blog
        url: blog
      # - name: CV
      #   url: cv.pdf

  socialIcons:
    - name: telegram
      url: "https://t.me/axaratox"
    - name: github
      url: "https://github.com/axaratox"
    - name: linkedin
      url: "https://www.linkedin.com/in/axaratox/"

  cover:
    hidden: false

  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    style: monokai